// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvRhsEQu2Ad24oKaO2LBfh2C9k4rDpjl8',
    appId: '1:912497100565:android:ceba9c381894f71ad30b1c',
    messagingSenderId: '912497100565',
    projectId: 'e-commerceapp-bf093',
    storageBucket: 'e-commerceapp-bf093.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-z2-qorpj1Ahkykm2juWDsHnDjqEOYMw',
    appId: '1:912497100565:ios:680bae63ec5411b9d30b1c',
    messagingSenderId: '912497100565',
    projectId: 'e-commerceapp-bf093',
    storageBucket: 'e-commerceapp-bf093.firebasestorage.app',
    iosClientId:
        '912497100565-7mf0e0hu9fauiiblvhqc2l5jbcpi632c.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
